name: Main Workflow
on: push
jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Run GolangCI-Lint
        id: run_golangci_lint
        uses: golangci/golangci-lint-action@v2
  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs:
    - lint
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
    - name: Set Up QEMU
      id: set_up_qemu
      uses: docker/setup-qemu-action@v1
    - name: Set Up Buildx
      id: set_up_buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Packages Docker Registry
      id: docker_login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build HTTP Server
      id: build_http_server
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: scripts/docker/Dockerfile.http-server
        tags: ghcr.io/morozovcookie/nomad-usage-example/http-server:${{ github.sha }}
    - name: Build gRPC Server
      id: build_grpc_server
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: scripts/docker/Dockerfile.grpc-server
        tags: ghcr.io/morozovcookie/nomad-usage-example/grpc-server:${{ github.sha }}
